---
title: Push Button Stop Motion
hero_image: images/banner.png
description: Make your own stop motion animation rig with a push button, using Python
  Picamera and GPIO
original_url: https://raspberrypi.org/learning/push-button-stop-motion
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: photography
technologies: electronic-components, python, pi-camera
site_areas: projects
hardware: electronic-components
software: python
version: 3.0.1
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Connect the camera
  completion:
  - engaged
- title: Take a picture with Python
- title: Connect a hardware button
- title: Take a selfie
- title: Stop motion animation
- title: Generate the video
  completion:
  - internal
  completion:
  - external
- title: What next?
